/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as MasculinoRouteImport } from './routes/masculino'
import { Route as FemininoRouteImport } from './routes/feminino'
import { Route as ColecoesRouteImport } from './routes/colecoes'
import { Route as AcessoriosRouteImport } from './routes/acessorios'
import { Route as IndexRouteImport } from './routes/index'

const MasculinoRoute = MasculinoRouteImport.update({
  id: '/masculino',
  path: '/masculino',
  getParentRoute: () => rootRouteImport,
} as any)
const FemininoRoute = FemininoRouteImport.update({
  id: '/feminino',
  path: '/feminino',
  getParentRoute: () => rootRouteImport,
} as any)
const ColecoesRoute = ColecoesRouteImport.update({
  id: '/colecoes',
  path: '/colecoes',
  getParentRoute: () => rootRouteImport,
} as any)
const AcessoriosRoute = AcessoriosRouteImport.update({
  id: '/acessorios',
  path: '/acessorios',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/acessorios': typeof AcessoriosRoute
  '/colecoes': typeof ColecoesRoute
  '/feminino': typeof FemininoRoute
  '/masculino': typeof MasculinoRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/acessorios': typeof AcessoriosRoute
  '/colecoes': typeof ColecoesRoute
  '/feminino': typeof FemininoRoute
  '/masculino': typeof MasculinoRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/acessorios': typeof AcessoriosRoute
  '/colecoes': typeof ColecoesRoute
  '/feminino': typeof FemininoRoute
  '/masculino': typeof MasculinoRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/acessorios' | '/colecoes' | '/feminino' | '/masculino'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/acessorios' | '/colecoes' | '/feminino' | '/masculino'
  id:
    | '__root__'
    | '/'
    | '/acessorios'
    | '/colecoes'
    | '/feminino'
    | '/masculino'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AcessoriosRoute: typeof AcessoriosRoute
  ColecoesRoute: typeof ColecoesRoute
  FemininoRoute: typeof FemininoRoute
  MasculinoRoute: typeof MasculinoRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/masculino': {
      id: '/masculino'
      path: '/masculino'
      fullPath: '/masculino'
      preLoaderRoute: typeof MasculinoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/feminino': {
      id: '/feminino'
      path: '/feminino'
      fullPath: '/feminino'
      preLoaderRoute: typeof FemininoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/colecoes': {
      id: '/colecoes'
      path: '/colecoes'
      fullPath: '/colecoes'
      preLoaderRoute: typeof ColecoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/acessorios': {
      id: '/acessorios'
      path: '/acessorios'
      fullPath: '/acessorios'
      preLoaderRoute: typeof AcessoriosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AcessoriosRoute: AcessoriosRoute,
  ColecoesRoute: ColecoesRoute,
  FemininoRoute: FemininoRoute,
  MasculinoRoute: MasculinoRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
